### PR TITLE
Correction d'une référence et une classe inexistante.

### PR DESCRIPTION
**Pull request by QuentinLemCode**
Bug fixing

### CODE REVIEW

**Comment by QuentinLemCode** [comment]
Quelque chose ne va pas ?

Is something wrong ?

**Comment by ZenSide** [comment]
Thanks for your pull request and sorry for the not yet merge. This bundle is closely related to another private project, so we cannot merge your change right now. Need a little cleanup to be fully generic :)
Did you already succeed to use it with your fix ?

**Comment by QuentinLemCode** [comment]
Ok, but I think you should delete the package from packagist because it is not usable in actual state. I have succeed to upload images with my fix. However, there was problem to retrieve images, but I think this is caused by folder path in development environment.
I didn't use this package anymore, i have choosen to integrate SonataMediaBundle. But I wanted to be sure there was no problem.

**Comment by ZenSide** [comment]
Ok, thanks for your return I take note and will change that

**Pull request merged**
